### ISSUE TITLE
Too many arguments in migrateAccount (reassignAllUser1ItemsToUser2())

### ISSUE THREAD

**Issue by cdtaylor** [Esri/ago-tools#42]
Hello,
I'm trying to migrate to enterprise logins and was testing the migrateAccounts sample.  When I try using either a single account or a csv file I get the error:

TypeError: reassignAllUser1ItemsToUser2() takes exactly 3 arguments (4 given)

Our enterprise logins are structured like '<username>@city.kingston.on.ca_<ago instance name>' (not sure if this is consistent across all enterprise login usernames or specific to us).  I wondered whether the issue was coming from the '@' symbol, so I tried to use re.escape to properly format the username:

userTo = re.escape('<enterprise login string>')
myAgol.migrateAccount('<userFrom>', userTo)

but I'm getting the same error.  I've tried lots of different combinations of escape characters and quotes but haven't landed on the right one yet.  Any ideas?

Thanks,
Chris

**Comment by ecaldwell** [comment]
In my testing, `@` didn't cause any problems. Are you providing a username for the `userFrom` parameter? Your sample has a blank string there.

**Comment by cdtaylor** [comment]
Hi Evan,
Thanks for the quick response!   Good to know re '@'.  Here's  my modified code:
***from agoTools.admin import AdminmyAgol = Admin('taylorchrisd')  # Replace <username> your ADMIN account
# for migrating a single account...myAgol.migrateAccount('taylorchrisd', 'ctaylor@city.kingston.on.ca_cokeltest')   # Replace with usernames between which you are moving items
# for migrating a batch of accounts...#myAgol.migrateAccounts(<path to user mapping CSV>)   # Replace with path to CSV file with col1=userFrom, col2=userTo
***
And the output:
***Warning (from warnings module):  File "C:\python27\ArcGIS10.3\lib\getpass.py", line 92    return fallback_getpass(prompt, stream)GetPassWarning: Can not control echo on the terminal.Warning: Password input may be echoed.Password: ********Copying all items from taylorchrisd to ctaylor@city.kingston.on.ca_cokeltest...
Traceback (most recent call last):  File "C:\python\modules\agoTools\samples\migrateAccount.py", line 12, in <module>    myAgol.migrateAccount('taylorchrisd', 'ctaylor@city.kingston.on.ca_cokeltest')   # Replace with usernames between which you are moving items  File "c:\python\modules\agoTools\admin.py", line 201, in migrateAccount    self.reassignAllUser1ItemsToUser2(self, userFrom, userTo)TypeError: reassignAllUser1ItemsToUser2() takes exactly 3 arguments (4 given)>>> 
Date: Fri, 22 May 2015 10:07:57 -0700

**Comment by cdtaylor** [comment]
Maybe there's something bigger going on with my machine/install.  I just got a similar error ('takes exactly 2 arguments (3 given)') with a different script (AGOLCat):
CSV path: c:\temp\test.csv #tried this both with just the path vs specifying file nameUsername:taylorchrisdPortal: cokeltest
Warning (from warnings module):  File "C:\python27\ArcGIS10.3\lib\getpass.py", line 92    return fallback_getpass(prompt, stream)GetPassWarning: Can not control echo on the terminal.Warning: Password input may be echoed.Password: ********
Traceback (most recent call last):  File "C:\python\modules\agoTools\samples\AGOLCat.py", line 87, in <module>    agoAdmin = Admin(args.user,args.portal,args.password)  File "c:\python\modules\agoTools\admin.py", line 14, in __init__    self.user = User(username, portal, password)  File "c:\python\modules\agoTools\__init__.py", line 19, in __init__    self.token = self.__getToken__(self.portalUrl, self.username, self.password)  File "c:\python\modules\agoTools\__init__.py", line 29, in __getToken__    response = urllib.urlopen(url + '/sharing/rest/generateToken?', parameters).read()  File "C:\python27\ArcGIS10.3\lib\urllib.py", line 89, in urlopen    return opener.open(url, data)  File "C:\python27\ArcGIS10.3\lib\urllib.py", line 210, in open    return getattr(self, name)(url, data)TypeError: open_file() takes exactly 2 arguments (3 given)>>> 
From: cdtaylor54@hotmail.com
To: reply@reply.github.com
Subject: RE: [ago-tools] Too many arguments in migrateAccount (reassignAllUser1ItemsToUser2()) (#42)
Date: Fri, 22 May 2015 13:25:28 -0400




Hi Evan,
Thanks for the quick response!   Good to know re '@'.  Here's  my modified code:
***from agoTools.admin import AdminmyAgol = Admin('taylorchrisd')  # Replace <username> your ADMIN account
# for migrating a single account...myAgol.migrateAccount('taylorchrisd', 'ctaylor@city.kingston.on.ca_cokeltest')   # Replace with usernames between which you are moving items
# for migrating a batch of accounts...#myAgol.migrateAccounts(<path to user mapping CSV>)   # Replace with path to CSV file with col1=userFrom, col2=userTo
***
And the output:
***Warning (from warnings module):  File "C:\python27\ArcGIS10.3\lib\getpass.py", line 92    return fallback_getpass(prompt, stream)GetPassWarning: Can not control echo on the terminal.Warning: Password input may be echoed.Password: ********Copying all items from taylorchrisd to ctaylor@city.kingston.on.ca_cokeltest...
Traceback (most recent call last):  File "C:\python\modules\agoTools\samples\migrateAccount.py", line 12, in <module>    myAgol.migrateAccount('taylorchrisd', 'ctaylor@city.kingston.on.ca_cokeltest')   # Replace with usernames between which you are moving items  File "c:\python\modules\agoTools\admin.py", line 201, in migrateAccount    self.reassignAllUser1ItemsToUser2(self, userFrom, userTo)TypeError: reassignAllUser1ItemsToUser2() takes exactly 3 arguments (4 given)>>> 
Date: Fri, 22 May 2015 10:07:57 -0700

**Comment by cdtaylor** [comment]
Hi again Evan,
I removed the 'self' argument from within the parentheses on line 201 in admin.py (migrateAccount):

self.reassignAllUser1ItemsToUser2(userFrom, userTo)
and it got past that call in the script when I tested it (and failed on the next one):
***Warning (from warnings module):  File "C:\python27\ArcGIS10.3\lib\getpass.py", line 92    return fallback_getpass(prompt, stream)GetPassWarning: Can not control echo on the terminal.Warning: Password input may be echoed.Password: ******Copying all items from taylorchrisd to ctaylor@city.kingston.on.ca_cokeltest...    1 ITEMS in 1 FOLDERS (incl. Home folder) copied        from USER taylorchrisd to USER ctaylor@city.kingston.on.ca_cokeltest
Reassigning groups owned by taylorchrisd to ctaylor@city.kingston.on.ca_cokeltest...
Traceback (most recent call last):  File "C:\python\modules\agoTools\samples\migrateAccount_cokeltest.py", line 15, in <module>    myAgol.migrateAccount('taylorchrisd', 'ctaylor@city.kingston.on.ca_cokeltest')   # Replace with usernames between which you are moving items  File "c:\python\modules\agoTools\admin.py", line 205, in migrateAccount    self.reassignAllGroupOwnership(self, userFrom, userTo)TypeError: reassignAllGroupOwnership() takes exactly 3 arguments (4 given)>>> 
***
I'm just happy I know how to work around it, but any idea why this might be affecting me, but didn't come up in your testing (or nobody else has reported this issue)?
From: cdtaylor54@hotmail.com
To: reply@reply.github.com
Subject: RE: [ago-tools] Too many arguments in migrateAccount (reassignAllUser1ItemsToUser2()) (#42)
Date: Fri, 22 May 2015 13:37:42 -0400




Maybe there's something bigger going on with my machine/install.  I just got a similar error ('takes exactly 2 arguments (3 given)') with a different script (AGOLCat):
CSV path: c:\temp\test.csv #tried this both with just the path vs specifying file nameUsername:taylorchrisdPortal: cokeltest
Warning (from warnings module):  File "C:\python27\ArcGIS10.3\lib\getpass.py", line 92    return fallback_getpass(prompt, stream)GetPassWarning: Can not control echo on the terminal.Warning: Password input may be echoed.Password: ********
Traceback (most recent call last):  File "C:\python\modules\agoTools\samples\AGOLCat.py", line 87, in <module>    agoAdmin = Admin(args.user,args.portal,args.password)  File "c:\python\modules\agoTools\admin.py", line 14, in __init__    self.user = User(username, portal, password)  File "c:\python\modules\agoTools\__init__.py", line 19, in __init__    self.token = self.__getToken__(self.portalUrl, self.username, self.password)  File "c:\python\modules\agoTools\__init__.py", line 29, in __getToken__    response = urllib.urlopen(url + '/sharing/rest/generateToken?', parameters).read()  File "C:\python27\ArcGIS10.3\lib\urllib.py", line 89, in urlopen    return opener.open(url, data)  File "C:\python27\ArcGIS10.3\lib\urllib.py", line 210, in open    return getattr(self, name)(url, data)TypeError: open_file() takes exactly 2 arguments (3 given)>>> 
From: cdtaylor54@hotmail.com
To: reply@reply.github.com
Subject: RE: [ago-tools] Too many arguments in migrateAccount (reassignAllUser1ItemsToUser2()) (#42)
Date: Fri, 22 May 2015 13:25:28 -0400




Hi Evan,
Thanks for the quick response!   Good to know re '@'.  Here's  my modified code:
***from agoTools.admin import AdminmyAgol = Admin('taylorchrisd')  # Replace <username> your ADMIN account
# for migrating a single account...myAgol.migrateAccount('taylorchrisd', 'ctaylor@city.kingston.on.ca_cokeltest')   # Replace with usernames between which you are moving items
# for migrating a batch of accounts...#myAgol.migrateAccounts(<path to user mapping CSV>)   # Replace with path to CSV file with col1=userFrom, col2=userTo
***
And the output:
***Warning (from warnings module):  File "C:\python27\ArcGIS10.3\lib\getpass.py", line 92    return fallback_getpass(prompt, stream)GetPassWarning: Can not control echo on the terminal.Warning: Password input may be echoed.Password: ********Copying all items from taylorchrisd to ctaylor@city.kingston.on.ca_cokeltest...
Traceback (most recent call last):  File "C:\python\modules\agoTools\samples\migrateAccount.py", line 12, in <module>    myAgol.migrateAccount('taylorchrisd', 'ctaylor@city.kingston.on.ca_cokeltest')   # Replace with usernames between which you are moving items  File "c:\python\modules\agoTools\admin.py", line 201, in migrateAccount    self.reassignAllUser1ItemsToUser2(self, userFrom, userTo)TypeError: reassignAllUser1ItemsToUser2() takes exactly 3 arguments (4 given)>>> 
Date: Fri, 22 May 2015 10:07:57 -0700
