### ISSUE TITLE
Unable log in as Admin using enterprise account

### ISSUE THREAD

**Issue by justingreco** [Esri/ago-tools#43]
When attempting to log in with the Admin command when using my enterprise account, I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/grecoj/agoTools/admin.py", line 16, in __init__
    self.user = User(username, portal, password)
  File "/Users/grecoj/agoTools/__init__.py", line 19, in __init__
    self.token = self.__getToken__(self.portalUrl, self.username, self.password)
  File "/Users/grecoj/agoTools/__init__.py", line 30, in __getToken__
    response = urllib.urlopen(url + '/sharing/rest/generateToken?', parameters).read()
KeyError: 'token'
```
There are no issues logging in with a non-enterprise account.

**Comment by ecaldwell** [comment]
Is this IWA/PKI or another enterprise identity provider?

**Comment by justingreco** [comment]
I failed to mention it was ADFS, I am sure that will help.  Not sure about the IWA/PKI, checking with the person that implemented it.

**Comment by ecaldwell** [comment]
Unfortunately, this doesn't handle anything other than vanilla portal user store login. If you need an immediate solution, I recommend you check out [ArcREST](https://github.com/Esri/ArcREST). They've done a nice job building in all kinds of security handlers.

**Comment by msokolDOIT** [comment]
I'm running into what I think is a similar issue with this.
I've tried transferring as an admin from an enterprise account but run into issues.  I seem to get further by using an agol hosted account.  We're looking to migrate all of our agol hosted accounts to enterprise accounts for single sign on.  I'm getting errors based on TypeError: open_file() takes exactly 2 arguments (3 given)
